server:
  port: 8081
customer-service:
  get-customers:
    endpoint: http://localhost:${server.port}/customers/{customerId}
auth-service:
  secret: asdfghjklwertyuisdfghjertyuixcvbnmertyuicvbmwertyuidfghjklcvbnmfghjkl
  token:
    expiryInSeconds: 2
  generateToken:
    endpoint: http://localhost:${server.port}/auth/token
  validateToken:
    endpoint: http://localhost:${server.port}/auth/token/{token}/isValid
  claims:
    endpoint: http://localhost:${server.port}/auth/token/{token}/claims
token:
  signing:
    method: ${TOKEN_SIGNING_METHOD:Symmetric}
